### ISSUE TITLE
Scaling to multiple instances after having an instance installed

### ISSUE THREAD

**Issue by phinwww** [DanWin/hosting#135] opened 2024-04-08 14:29 UTC
Hey,

Theoretically, would it be possible to have multiple instances of Daniel’s Hosting across multiple servers? Let’s just say I wanted to spread resources out and have one site on one server, another site on another server, etc. while having the same database. Is this possible to implement?

**Comment by DanWin** [comment] 2024-04-08 14:40
Hey @phinwww , yes in theory this would be possible. There is already another issue for this: #78 Essentially the database should be run in clustering and ideally also the file system. Then for each instance there needs to be added a server field that will keep track on which server a given instance is running. I will close this as a duplicate of the existing issue.

**Closed by DanWin** 2024-04-08 14:40 UTC
