### ISSUE TITLE
unzip not work in FileMnager

### ISSUE THREAD

**Issue by sergrych** [DanWin/hosting#125] opened 2022-06-05 01:30 UTC
mkdir- work
mkfile - work
rename - work
delete - work
unzip -no work

help what to check?

**Comment by DEAM0** [comment] 2022-06-05 13:10
sudo apt-get install unzip

**Comment by sergrych** [comment] 2022-06-06 08:40
> sudo apt-get install unzip

no, unzip installed

**Comment by DEAM0** [comment] 2022-06-12 19:17
yeah not work for me too

**Comment by sergrych** [comment] 2022-06-25 13:29
do
export PATH=$PATH:/usr/sbin
or
sh -c 'echo "export PATH=$PATH:/usr/sbin" >> ~/.bashrc'

**Comment by DanWin** [comment] 2022-07-02 09:51
The file manager issues an unzip command to the chrooted user directory. Some systems have a symlink for `/bin` and `/lib`, which previously caused issues when creating the chroot. If that is the case for you, it most likely is the issue you are experiencing. This is fixed in 07b2fd0650cf8f2b3548b5303fd9ff52a829b55d. When you have applied the latest changes, simply set `SKIP_USER_CHROOT_UPDATE = false;` in `common.php` and re-run the `setup.php` script, which will then update all user chroots. (This will take some time)
I think this is likely the cause, so I'm closing this issue. If you still have an issue with unzip after applying the change, feel free to re-open.

**Closed by DanWin** 2022-07-02 09:51 UTC
